---
name: napari-folder-browser
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.1
  - napari-plugin-engine=0.2.0
  - napari-tools-menu=0.1.19

# Test dependencies (optional)
  - PyQt5=5.15.10
  - pytest=8.1.1